//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4
        ///
        ///12
        ///12
        ///
        ///1537983
        ///23606766456
        ///
        ///377773935827991229645029714898969028
        ///301174256660595384532197942652815288956047581636
        ///
        ///1242468682113840180763850624340867898830637122775434796573473991466933960634085363735808574823872230131509619596260435331836866582052453403290874467870290043697815376935298110895904163169442926407335197820883439691250684070655002714487685888
        ///417545487977981564551173186152102228498479694796653351848954185997611243506278579601980980219484255929864359810447039931
        ///
        ///
        ///.
        /// </summary>
        internal static string AddTestCases {
            get {
                return ResourceManager.GetString("AddTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4
        ///
        ///12
        ///12
        ///
        ///1537983
        ///23606766456
        ///
        ///377773935827991229645029714898969028
        ///301174256660595384532197942652815288956047581636
        ///
        ///3100675333279421257617608000138708458801868104897830766303748759001197941598947667658921326203715302820376126044350727358334784388707871335695033578987322915001084651142521380653788065896776145986861827114585345797313243712035560159039288370426232610063160693819476708720025406607223686363847361116574606364158447113777534349736920690749819066439287617387982955
        ///11713696775970099287 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiplyTestCases {
            get {
                return ResourceManager.GetString("MultiplyTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5
        ///
        ///12
        ///12
        ///
        ///23606766456
        ///1537983
        ///
        ///301174256660595384532197942652815288956047581636
        ///377773935827991229645029714898969028
        ///
        ///1242468682113840180763850624340867898830637122775434796573473991466933960634085363735808574823872230131509619596260435331836866582052453403290874467870290043697815376935298110895904163169442926407335197820883439691250684070655002714487685888
        ///417545487977981564551173186152102228498479694796653351848954185997611243506278579601980980219484255929864359810447039931
        ///
        ///4746065774778736 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SubtractTestCases {
            get {
                return ResourceManager.GetString("SubtractTestCases", resourceCulture);
            }
        }
    }
}
